name: انتشار رابط کاربری گرافیکی

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: دریافت کدها
        uses: actions/checkout@v3

      - name: برپایی GitHub Pages
        uses: actions/configure-pages@v3

      - name: آپلود آرتیفکت
        uses: actions/upload-pages-artifact@v2
        with:
          path: 'alpha-gui'

      - name: انتشار در GitHub Pages
        uses: actions/deploy-pages@v2
